export type {
  BetAction,
  Bet,
  BettingRound,
  Blinds,
  CardScore,
  CardScoreData,
  Confederation,
  Fixture,
  FixtureStatus,
  GameState,
  MatchResult,
  MatchStage,
  PlayerHand,
  Round,
  RoundStatus,
  ShowdownResult,
  Table,
  TablePlayer,
  TableStatus,
  Team,
  TeamCard,
  TeamTier,
  User,
} from './types/game.types.js'

export type {
  BetPromptPayload,
  BetUpdatePayload,
  ClientToServerEvents,
  FixtureResultPayload,
  LobbyTableItem,
  PlayerActionPayload,
  PlayerScoredPayload,
  RoundCardPayload,
  RoundPausePayload,
  RoundResultsPayload,
  RoundStartPayload,
  RoundWinnerPayload,
  ServerToClientEvents,
} from './types/socket-events.js'

export { calculateCardScore, calculateHandScore, determineWinners } from './utils/scoring.js'
