import 'dotenv/config'
import pg from 'pg'
import { drizzle } from 'drizzle-orm/node-postgres'
import { teams } from '../schema.js'

const TEAMS_DATA = [
  {
    id: 'ARG',
    name: 'Argentina',
    confederation: 'CONMEBOL',
    wcGroup: 'A',
    flagEmoji: '\u{1F1E6}\u{1F1F7}',
    fifaRanking: 1,
    tier: 'S',
  },
  {
    id: 'FRA',
    name: 'France',
    confederation: 'UEFA',
    wcGroup: 'B',
    flagEmoji: '\u{1F1EB}\u{1F1F7}',
    fifaRanking: 2,
    tier: 'S',
  },
  {
    id: 'BRA',
    name: 'Brazil',
    confederation: 'CONMEBOL',
    wcGroup: 'C',
    flagEmoji: '\u{1F1E7}\u{1F1F7}',
    fifaRanking: 3,
    tier: 'S',
  },
  {
    id: 'ENG',
    name: 'England',
    confederation: 'UEFA',
    wcGroup: 'D',
    flagEmoji: '\u{1F3F4}\u{E0067}\u{E0062}\u{E0065}\u{E006E}\u{E0067}\u{E007F}',
    fifaRanking: 4,
    tier: 'S',
  },
  {
    id: 'ESP',
    name: 'Spain',
    confederation: 'UEFA',
    wcGroup: 'E',
    flagEmoji: '\u{1F1EA}\u{1F1F8}',
    fifaRanking: 5,
    tier: 'S',
  },
  {
    id: 'GER',
    name: 'Germany',
    confederation: 'UEFA',
    wcGroup: 'F',
    flagEmoji: '\u{1F1E9}\u{1F1EA}',
    fifaRanking: 6,
    tier: 'A',
  },
  {
    id: 'POR',
    name: 'Portugal',
    confederation: 'UEFA',
    wcGroup: 'G',
    flagEmoji: '\u{1F1F5}\u{1F1F9}',
    fifaRanking: 7,
    tier: 'A',
  },
  {
    id: 'NED',
    name: 'Netherlands',
    confederation: 'UEFA',
    wcGroup: 'H',
    flagEmoji: '\u{1F1F3}\u{1F1F1}',
    fifaRanking: 8,
    tier: 'A',
  },
  {
    id: 'BEL',
    name: 'Belgium',
    confederation: 'UEFA',
    wcGroup: 'A',
    flagEmoji: '\u{1F1E7}\u{1F1EA}',
    fifaRanking: 9,
    tier: 'A',
  },
  {
    id: 'ITA',
    name: 'Italy',
    confederation: 'UEFA',
    wcGroup: 'B',
    flagEmoji: '\u{1F1EE}\u{1F1F9}',
    fifaRanking: 10,
    tier: 'A',
  },
  {
    id: 'CRO',
    name: 'Croatia',
    confederation: 'UEFA',
    wcGroup: 'C',
    flagEmoji: '\u{1F1ED}\u{1F1F7}',
    fifaRanking: 11,
    tier: 'B',
  },
  {
    id: 'URU',
    name: 'Uruguay',
    confederation: 'CONMEBOL',
    wcGroup: 'D',
    flagEmoji: '\u{1F1FA}\u{1F1FE}',
    fifaRanking: 12,
    tier: 'B',
  },
  {
    id: 'COL',
    name: 'Colombia',
    confederation: 'CONMEBOL',
    wcGroup: 'E',
    flagEmoji: '\u{1F1E8}\u{1F1F4}',
    fifaRanking: 13,
    tier: 'B',
  },
  {
    id: 'DEN',
    name: 'Denmark',
    confederation: 'UEFA',
    wcGroup: 'F',
    flagEmoji: '\u{1F1E9}\u{1F1F0}',
    fifaRanking: 14,
    tier: 'B',
  },
  {
    id: 'JPN',
    name: 'Japan',
    confederation: 'AFC',
    wcGroup: 'G',
    flagEmoji: '\u{1F1EF}\u{1F1F5}',
    fifaRanking: 15,
    tier: 'B',
  },
  {
    id: 'MAR',
    name: 'Morocco',
    confederation: 'CAF',
    wcGroup: 'H',
    flagEmoji: '\u{1F1F2}\u{1F1E6}',
    fifaRanking: 16,
    tier: 'B',
  },
  {
    id: 'SEN',
    name: 'Senegal',
    confederation: 'CAF',
    wcGroup: 'A',
    flagEmoji: '\u{1F1F8}\u{1F1F3}',
    fifaRanking: 17,
    tier: 'B',
  },
  {
    id: 'USA',
    name: 'United States',
    confederation: 'CONCACAF',
    wcGroup: 'B',
    flagEmoji: '\u{1F1FA}\u{1F1F8}',
    fifaRanking: 18,
    tier: 'B',
  },
  {
    id: 'MEX',
    name: 'Mexico',
    confederation: 'CONCACAF',
    wcGroup: 'C',
    flagEmoji: '\u{1F1F2}\u{1F1FD}',
    fifaRanking: 19,
    tier: 'C',
  },
  {
    id: 'CAN',
    name: 'Canada',
    confederation: 'CONCACAF',
    wcGroup: 'D',
    flagEmoji: '\u{1F1E8}\u{1F1E6}',
    fifaRanking: 20,
    tier: 'C',
  },
  {
    id: 'AUS',
    name: 'Australia',
    confederation: 'AFC',
    wcGroup: 'E',
    flagEmoji: '\u{1F1E6}\u{1F1FA}',
    fifaRanking: 21,
    tier: 'C',
  },
  {
    id: 'KOR',
    name: 'South Korea',
    confederation: 'AFC',
    wcGroup: 'F',
    flagEmoji: '\u{1F1F0}\u{1F1F7}',
    fifaRanking: 22,
    tier: 'C',
  },
  {
    id: 'KSA',
    name: 'Saudi Arabia',
    confederation: 'AFC',
    wcGroup: 'G',
    flagEmoji: '\u{1F1F8}\u{1F1E6}',
    fifaRanking: 23,
    tier: 'C',
  },
  {
    id: 'IRN',
    name: 'Iran',
    confederation: 'AFC',
    wcGroup: 'H',
    flagEmoji: '\u{1F1EE}\u{1F1F7}',
    fifaRanking: 24,
    tier: 'C',
  },
  {
    id: 'ECU',
    name: 'Ecuador',
    confederation: 'CONMEBOL',
    wcGroup: 'A',
    flagEmoji: '\u{1F1EA}\u{1F1E8}',
    fifaRanking: 25,
    tier: 'C',
  },
  {
    id: 'SRB',
    name: 'Serbia',
    confederation: 'UEFA',
    wcGroup: 'B',
    flagEmoji: '\u{1F1F7}\u{1F1F8}',
    fifaRanking: 26,
    tier: 'C',
  },
  {
    id: 'SUI',
    name: 'Switzerland',
    confederation: 'UEFA',
    wcGroup: 'C',
    flagEmoji: '\u{1F1E8}\u{1F1ED}',
    fifaRanking: 27,
    tier: 'C',
  },
  {
    id: 'POL',
    name: 'Poland',
    confederation: 'UEFA',
    wcGroup: 'D',
    flagEmoji: '\u{1F1F5}\u{1F1F1}',
    fifaRanking: 28,
    tier: 'C',
  },
  {
    id: 'WAL',
    name: 'Wales',
    confederation: 'UEFA',
    wcGroup: 'E',
    flagEmoji: '\u{1F3F4}\u{E0067}\u{E0062}\u{E0077}\u{E006C}\u{E0073}\u{E007F}',
    fifaRanking: 29,
    tier: 'C',
  },
  {
    id: 'TUN',
    name: 'Tunisia',
    confederation: 'CAF',
    wcGroup: 'F',
    flagEmoji: '\u{1F1F9}\u{1F1F3}',
    fifaRanking: 30,
    tier: 'C',
  },
  {
    id: 'CMR',
    name: 'Cameroon',
    confederation: 'CAF',
    wcGroup: 'G',
    flagEmoji: '\u{1F1E8}\u{1F1F2}',
    fifaRanking: 31,
    tier: 'C',
  },
  {
    id: 'GHA',
    name: 'Ghana',
    confederation: 'CAF',
    wcGroup: 'H',
    flagEmoji: '\u{1F1EC}\u{1F1ED}',
    fifaRanking: 32,
    tier: 'C',
  },
] as const

async function seed() {
  const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL })
  const database = drizzle(pool)

  try {
    console.log('Seed - start', { teamCount: TEAMS_DATA.length })

    await database.delete(teams)

    await database.insert(teams).values([...TEAMS_DATA])

    console.log('Seed - complete', { inserted: TEAMS_DATA.length })
  } catch (error) {
    console.error('Seed - failed', { error })
    process.exit(1)
  } finally {
    await pool.end()
  }
}

seed()
